### ISSUE TITLE
unsafe_settings - validation error

### ISSUE THREAD

**Issue by spsach** [zylon-ai/private-gpt#1774]
I have tried to install it on Ubuntu with ollama:mistral and followed the process as per the installation manual. I am getting the following error with unsafe_settings. Any ideas?

ubuntu@ip-172-31-24-190:~/privateGPT$ make run
poetry run python -m private_gpt
***** CLASS SETTINGS*****
UI: <class 'private_gpt.settings.settings.Settings'>
22:23:29.345 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'ollama']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ubuntu/privateGPT/private_gpt/__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "/home/ubuntu/privateGPT/private_gpt/main.py", line 3, in <module>
    from private_gpt.di import global_injector
  File "/home/ubuntu/privateGPT/private_gpt/di.py", line 3, in <module>
    from private_gpt.settings.settings import Settings, unsafe_typed_settings
  File "/home/ubuntu/privateGPT/private_gpt/settings/settings.py", line 398, in <module>
    unsafe_typed_settings = Settings(**unsafe_settings)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/private-gpt-Wtvj2B-w-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Settings
azopenai
  Field required [type=missing, input_value={'server': {'env_name': '...del': 'mistral:latest'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
nodestore
  Field required [type=missing, input_value={'server': {'env_name': '...del': 'mistral:latest'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
make: *** [Makefile:36: run] Error 1

**Comment by spsach** [comment]
I have set PGPT_PROFILES=ollama, Python 3.11, Ubuntu 22.04.
make run always giving this error. unsafe_typed_settings = Settings(**unsafe_settings)

I have the same environment running properly on another machine

Has anyone else seen this error/problem?

**Comment by stevenlafl** [comment]
Yes. Using stock settings. No idea why.
