### ISSUE TITLE
A German document cannot be loaded (with Mistral and gemma:7b)

### ISSUE THREAD

**Issue by estkae** [zylon-ai/private-gpt#1788]
The same Dokument translate in English works
This is the Output:
08:20:15.351 [INFO    ] private_gpt.server.ingest.ingest_service - Ingesting file_names=['gert.pdf']
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 998.17it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1001.51it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1002.46it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1001.27it/s]
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1000.55it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 999.12it/s] 
Generating embeddings: 0it [00:00, ?it/s]
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s] 
Generating embeddings: 0it [00:00, ?it/s]
08:20:15.551 [INFO    ] private_gpt.server.ingest.ingest_service - Finished ingestion file_name=['gert.pdf']
08:20:15.614 [INFO    ]            uvicorn.access - 127.0.0.1:52197 - "POST /queue/join HTTP/1.1" 200
08:20:15.621 [INFO    ]            uvicorn.access - 127.0.0.1:52197 - "GET /queue/data?session_hash=ujyl0u8wdq9 HTTP/1.1" 200
08:20:15.684 [ERROR   ]                   asyncio - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\kae\miniconda3\envs\privategpt\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\kae\miniconda3\envs\privategpt\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
0

**Comment by jaluma** [comment]
Could you give us more details about profile, environment, machine?
