### ISSUE TITLE
After installing container privateGPT, container won't start

### ISSUE THREAD

**Issue by wiebereu** [zylon-ai/private-gpt#1789]
I install the container by using the docker compose file and the docker build file 
In my volume\docker\private-gpt folder I have my docker compose file and my dockerfile.local. 
at first, I ran into an error. That made me copy the pyproject.toml file to the root folder of private-gpt
That seems to work
I can build the image but if I run the docker-compose up it will not start the container and it comes with the following error

private-gpt  | /usr/local/bin/python: No module named private_gpt.__main__; 'private_gpt' is a package and cannot be directly executed

I thought because this is a container, all relevant files should be in the container. 
Am I missing something here?

**Comment by qdm12** [comment]
Try perhaps using my branch https://github.com/qdm12/private-gpt/tree/qdm12/dockerfile-1 (PR #1792)
with

```sh
docker build -t privategpt https://github.com/qdm12/private-gpt.git#dockerfile-1
```

With the image `privategpt`? I have it running fine. Don't forget to set environment variables to fit what's in [settings-docker.yaml](https://github.com/qdm12/private-gpt/blob/qdm12/dockerfile-1/settings-docker.yaml)

**Comment by wiebereu** [comment]
****

> Try perhaps using my branch https://github.com/qdm12/private-gpt/tree/qdm12/dockerfile-1 (PR #1792) with
> 
> ```shell
> docker build -t privategpt -f Dockerfile.external https://github.com/qdm12/private-gpt.git#dockerfile-1
> ```
> 
> With the image `privategpt`? I have it running fine. Don't forget to set environment variables to fit what's in [settings-docker.yaml](https://github.com/qdm12/private-gpt/blob/qdm12/dockerfile-1/settings-docker.yaml)

Thanks QDM12, 

Can it work with Ollama? I have a an ollama container and want PrivateGPT to work with it. 
Also how can I set the environment variable for a working container. Is there a docker-compose file?

**Comment by wiebereu** [comment]
To give an update

> Try perhaps using my branch https://github.com/qdm12/private-gpt/tree/qdm12/dockerfile-1 (PR #1792) with
> 
> ```shell
> docker build -t privategpt -f Dockerfile.external https://github.com/qdm12/private-gpt.git#dockerfile-1
> ```
> 
> With the image `privategpt`? I have it running fine. Don't forget to set environment variables to fit what's in [settings-docker.yaml](https://github.com/qdm12/private-gpt/blob/qdm12/dockerfile-1/settings-docker.yaml)

I wan to give you an update. 
i try you method by using this link that you provided: docker build -t privategpt -f Dockerfile.external https://github.com/qdm12/private-gpt.git#dockerfile-1

I couldn't run it because it says that it doesn't recognize dockerfile -1. 
I deleted everything from # till -1 and then it ran and built the image. However, I didn't see a way to run this image. I tried docker run and then the image hash but It resulted in an error. 
I decided to do it another way. I downloaded all the files with the command git clone and then the link to your repository. 
Then i did a docker compose build. 
It built the image and after that, i did a docker compose up. 
but to my disappointment, the docker container did not start. I think that I'm doing something wrong
This is the error message that i received 
     

```
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/home/worker/app/private_gpt/__main__.py", line 3, in <module>

    import uvicorn
```

I think that the problem lies in the way i built and run the image. I am doing something in the wrong order. 

This is my docker compose file that is use to start the image

ModuleNotFoundError: No module named 'uvicorn'



This is my docker compose file: 
`services:
  private-gpt:
    build:
      dockerfile: Dockerfile.local
    volumes:
      - /volume1/docker/private-gpt/local_data/:/home/worker/app/local_data
      - /volume1/docker/private-gpt/models/:/home/worker/app/models
      - /volume1/docker/private-gpt:/home/worker/app

    ports:
      - 8001:8080
    environment:
      PORT: 8080
      PGPT_PROFILES: docker
      PGPT_MODE: llm

I honestly can tell you what I'm doing wrong

**Comment by qdm12** [comment]
@wiebereu I fixed my command above, the `#dockerfile-1` was meant to be `#qdm12/dockerfile-1`. Please try rebuilding that one. Note the master branch on my fork is the same as the master branch here, so there is no point building it either.

For Ollama, you want to use `PGPT_MODE: ollama`. Now the problem is there is no definitions in settings-docker.yaml for Ollama so you cannot use environment variables for now - happy to add them after the PR I mentioned above gets merged, so you'll face a problem here. What I would suggest you is to copy the settings.yaml (from this repo or another), modify it to your liking, and then bind mount it as `./settings.yaml:/home/worker/app/private_gpt/settings-docker.yaml`, keeping only `PGPT_PROFILES: docker` (so it picks settings-docker.yaml). What you want to set in settings.yaml notably is:

- llm.mode to be `ollama`
- ollama section fields (llm_model, embedding_model, api_base)

So something (untested) similar to:

```yml
services:
  private-gpt:
    image: privategpt
    volumes:
      - ./local_data/:/home/worker/app/local_data
      - ./models/:/home/worker/app/models
      - ./settings.yaml:/home/worker/app/private_gpt/settings-docker.yaml:ro
    ports:
      - 8001:8080
    environment:
      PGPT_PROFILES: docker
```

**Comment by wiebereu** [comment]
> @wiebereu I fixed my command above, the `#dockerfile-1` was meant to be `#qdm12/dockerfile-1`. Please try rebuilding that one. Note the master branch on my fork is the same as the master branch here, so there is no point building it either.
> 
> For Ollama, you want to use `PGPT_MODE: ollama`. Now the problem is there is no definitions in settings-docker.yaml for Ollama so you cannot use environment variables for now - happy to add them after the PR I mentioned above gets merged, so you'll face a problem here. What I would suggest you is to copy the settings.yaml (from this repo or another), modify it to your liking, and then bind mount it as `./settings.yaml:/home/worker/app/private_gpt/settings-docker.yaml`, keeping only `PGPT_PROFILES: docker` (so it picks settings-docker.yaml). What you want to set in settings.yaml notably is:
> 
> * llm.mode to be `ollama`
> * ollama section fields (llm_model, embedding_model, api_base)
> 
> So something (untested) similar to:
> 
> ```yaml
> services:
>   private-gpt:
>     image: privategpt
>     volumes:
>       - ./local_data/:/home/worker/app/local_data
>       - ./models/:/home/worker/app/models
>       - ./settings.yaml:/home/worker/app/private_gpt/settings-docker.yaml:ro
>     ports:
>       - 8001:8080
>     environment:
>       PGPT_PROFILES: docker
> ```

I am trying to build the image according to what you stated in your first message, but how can I get the image to run? How I turn the build image into a container? Do I need to copy the settings-docker.ymal, docker-compose.yml, and dockerfile.local to my private-gpt folder first and run it? 

I decided to stick to your original llamacpp in the PGPT_MODE. To avoid any problems.

**Comment by qdm12** [comment]
> I am trying to build the image according to what you stated in your first message, but how can I get the image to run?

The image you built is named privategpt (flag `-t privategpt`), so just specify this in your docker-compose.yml with `image: privategpt` (already the case) and docker will pick it up from the built images it has stored.

> Do I need to copy the settings-docker.ymal, docker-compose.yml, and dockerfile.local to my private-gpt folder first and run it?

You only need:
- `docker-compose.yml`
- `settings.yaml` as described in above message, copy paste from https://github.com/zylon-ai/private-gpt/blob/main/settings.yaml and modify

The files needed to run the program are already in the Docker image you built, and you don't need the `Dockerfile.local` (or `Dockerfile.external`) which are only needed the BUILD the image, not to run the built image as a container. The image is already built using the command I gave you (Docker git cloned, changed branch then built the image all in one command).

Hopefully this clears it up. I will eventually add documentation for Docker once the maintainers approve a few PRs to have a more decent default Docker config, since right now it's a bit messy and not worth documenting before fixing.

**Comment by wiebereu** [comment]
I did manage to run the image. I build the image according to the link in the first message and than just run docker compose up -d and it starts the image. 

You mentioned that I can or must modify the settings in settings-docker.ymal. First I copy it to the root folder of private-gpt, but did not understand where to put these 2 things that you mentioned:
llm.mode to be ollama **where to put this n the settings-docker.ymal**
ollama section fields (llm_model, embedding_model, api_base)  **where to put this in the settings-docker.ymal**

I modify the docker-compose file and it is as follows: 
`services:
  private-gpt:
    build:
      dockerfile: Dockerfile.local
    volumes:
      - ./local_data/:/home/worker/app/local_data
      - ./models/:/home/worker/app/models
      - ./settings.yaml:/home/worker/app/private_gpt/settings-docker.yaml

    ports:
      - 8001:8080
    environment:
      PORT: 8080
      PGPT_PROFILES: docker
      PGPT_MODE: ollama
`

I tried all the other options before I ended with Ollama as PGPT_mode, cause only this way the container will start.

As I said I didn't modify the settings-docker.ymal as you can see here: 

`server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8080}

llm:
  mode: ${PGPT_MODE:mock}

embedding:
  mode: ${PGPT_EMBEDDING_MODE:sagemaker}

llamacpp:
  llm_hf_repo_id: ${PGPT_HF_REPO_ID:TheBloke/Mistral-7B-Instruct-v0.1-GGUF}
  llm_hf_model_file: ${PGPT_HF_MODEL_FILE:mistral-7b-instruct-v0.1.Q4_K_M.gguf}

huggingface:
  embedding_hf_model_name: ${PGPT_EMBEDDING_HF_MODEL_NAME:BAAI/bge-small-en-v1.5}

sagemaker:
  llm_endpoint_name: ${PGPT_SAGEMAKER_LLM_ENDPOINT_NAME:}
  embedding_endpoint_name: ${PGPT_SAGEMAKER_EMBEDDING_ENDPOINT_NAME:}

ui:
  enabled: true
  path: /
`

After doing this all the container starts, but then I get this error message: 

**PermissionError: [Errno 13] Permission denied: '/home/worker/app/models/cache'**

I am sorry that I am probably asking too much, I just want it to work

**Comment by aabhivyakt** [comment]
> I did manage to run the image. I build the image according to the link in the first message and than just run docker compose up -d and it starts the image.
> 
> You mentioned that I can or must modify the settings in settings-docker.ymal. First I copy it to the root folder of private-gpt, but did not understand where to put these 2 things that you mentioned: llm.mode to be ollama **where to put this n the settings-docker.ymal** ollama section fields (llm_model, embedding_model, api_base) **where to put this in the settings-docker.ymal**
> 
> I modify the docker-compose file and it is as follows: `services: private-gpt: build: dockerfile: Dockerfile.local volumes: - ./local_data/:/home/worker/app/local_data - ./models/:/home/worker/app/models - ./settings.yaml:/home/worker/app/private_gpt/settings-docker.yaml
> 
> ```
> ports:
>   - 8001:8080
> environment:
>   PORT: 8080
>   PGPT_PROFILES: docker
>   PGPT_MODE: ollama
> ```
> 
> `
> 
> I tried all the other options before I ended with Ollama as PGPT_mode, cause only this way the container will start.
> 
> As I said I didn't modify the settings-docker.ymal as you can see here:
> 
> `server: env_name: ${APP_ENV:prod} port: ${PORT:8080}
> 
> llm: mode: ${PGPT_MODE:mock}
> 
> embedding: mode: ${PGPT_EMBEDDING_MODE:sagemaker}
> 
> llamacpp: llm_hf_repo_id: ${PGPT_HF_REPO_ID:TheBloke/Mistral-7B-Instruct-v0.1-GGUF} llm_hf_model_file: ${PGPT_HF_MODEL_FILE:mistral-7b-instruct-v0.1.Q4_K_M.gguf}
> 
> huggingface: embedding_hf_model_name: ${PGPT_EMBEDDING_HF_MODEL_NAME:BAAI/bge-small-en-v1.5}
> 
> sagemaker: llm_endpoint_name: ${PGPT_SAGEMAKER_LLM_ENDPOINT_NAME:} embedding_endpoint_name: ${PGPT_SAGEMAKER_EMBEDDING_ENDPOINT_NAME:}
> 
> ui: enabled: true path: / `
> 
> After doing this all the container starts, but then I get this error message:
> 
> **PermissionError: [Errno 13] Permission denied: '/home/worker/app/models/cache'** **There was a problem when trying to write in your cache folder (/nonexistent/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.** **matplotlib - Matplotlib created a temporary cache directory at /tmp/matplotlib-ofvtqk2r because the default path (/nonexistent/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
> 
> 22:13:19.478 [INFO ] matplotlib.font_manager - generated new fontManager**
> 
> I am sorry that I am probably asking too much, I just want it to work

You need tto provide read and write permission to model/cache directory inside the container

**Comment by JavierMariosa** [comment]
> @wiebereu I fixed my command above, the `#dockerfile-1` was meant to be `#qdm12/dockerfile-1`. Please try rebuilding that one. Note the master branch on my fork is the same as the master branch here, so there is no point building it either.
> 
> For Ollama, you want to use `PGPT_MODE: ollama`. Now the problem is there is no definitions in settings-docker.yaml for Ollama so you cannot use environment variables for now - happy to add them after the PR I mentioned above gets merged, so you'll face a problem here. What I would suggest you is to copy the settings.yaml (from this repo or another), modify it to your liking, and then bind mount it as `./settings.yaml:/home/worker/app/private_gpt/settings-docker.yaml`, keeping only `PGPT_PROFILES: docker` (so it picks settings-docker.yaml). What you want to set in settings.yaml notably is:
> 
> * llm.mode to be `ollama`
> * ollama section fields (llm_model, embedding_model, api_base)
> 
> So something (untested) similar to:
> 
> ```yaml
> services:
>   private-gpt:
>     image: privategpt
>     volumes:
>       - ./local_data/:/home/worker/app/local_data
>       - ./models/:/home/worker/app/models
>       - ./settings.yaml:/home/worker/app/private_gpt/settings-docker.yaml:ro
>     ports:
>       - 8001:8080
>     environment:
>       PGPT_PROFILES: docker
> ```

Hello! I've been trying to use your docker branch as you stated, but it doesn't seem to (to my understanding) download the models or give me any chance to put local models. Your docker build executes this command:

 RUN poetry install --extras "ui vector-stores-qdrant"
 
 so it only installs the gradio ui and the vector database. It doesn't install llama-cpp or embeddings. The resulting image is about 800MB while if I build using the dockerfile.local, it's like 6.5GB
 
 None of them work. I even copied the variables in the yaml file when creating the container, but I guess I'm missing something obvious. Tell me if you need the docker output when it states the failure so we can follow up from there. Anyways, great work!!

**Comment by qdm12** [comment]
> Your docker build executes this command:
> 
> RUN poetry install --extras "ui vector-stores-qdrant"

Incorrect, see line https://github.com/qdm12/private-gpt/blob/798516c82577cf7b250e711072fb618c81d9aa99/Dockerfile.external#L17

Use `--build-arg POETRY_EXTRAS="..."` to define what extras you want in your Docker build command.

> but it doesn't seem to (to my understanding) download the models or give me any chance to put local models

Add `embeddings-huggingface` to your space separated list in POETRY_EXTRAS. For some obscure reason, it's not part of the default external Dockerfile, so I kept it that way for the time being (will PR this too, later).

If you want llama-cpp, you would need to use `-f Dockerfile.local` to have the build dependencies for it. I have a local branch merging both external and local Dockerfiles together and also reducing the llama-cpp docker image size quite a bit, but I'm waiting for that first PR to get merged. Unfortunately the maintainers seem rather slow reviewing PRs 😞  I'll comment here with simpler instructions and push that branch on my fork.

**Comment by qdm12** [comment]
See https://github.com/qdm12/private-gpt/pull/5 it has instructions on how to build (+tweak the build) the Docker image, and run it with an updated/hopefully-better docker-compose.yml.

**Comment by wiebereu** [comment]
> See [qdm12#5](https://github.com/qdm12/private-gpt/pull/5) it has instructions on how to build (+tweak the build) the Docker image, and run it with an updated/hopefully-better docker-compose.yml.

Thanks qdm12, you are a true helper. 
I can't get to it right now because i am not in the position to use my server, but when i get back i will try it and let you know

**Comment by wiebereu** [comment]
> > I did manage to run the image. I build the image according to the link in the first message and than just run docker compose up -d and it starts the image.
> > You mentioned that I can or must modify the settings in settings-docker.ymal. First I copy it to the root folder of private-gpt, but did not understand where to put these 2 things that you mentioned: llm.mode to be ollama **where to put this n the settings-docker.ymal** ollama section fields (llm_model, embedding_model, api_base) **where to put this in the settings-docker.ymal**
> > I modify the docker-compose file and it is as follows: `services: private-gpt: build: dockerfile: Dockerfile.local volumes: - ./local_data/:/home/worker/app/local_data - ./models/:/home/worker/app/models - ./settings.yaml:/home/worker/app/private_gpt/settings-docker.yaml
> > ```
> > ports:
> >   - 8001:8080
> > environment:
> >   PORT: 8080
> >   PGPT_PROFILES: docker
> >   PGPT_MODE: ollama
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `
> > I tried all the other options before I ended with Ollama as PGPT_mode, cause only this way the container will start.
> > As I said I didn't modify the settings-docker.ymal as you can see here:
> > `server: env_name: ${APP_ENV:prod} port: ${PORT:8080}
> > llm: mode: ${PGPT_MODE:mock}
> > embedding: mode: ${PGPT_EMBEDDING_MODE:sagemaker}
> > llamacpp: llm_hf_repo_id: ${PGPT_HF_REPO_ID:TheBloke/Mistral-7B-Instruct-v0.1-GGUF} llm_hf_model_file: ${PGPT_HF_MODEL_FILE:mistral-7b-instruct-v0.1.Q4_K_M.gguf}
> > huggingface: embedding_hf_model_name: ${PGPT_EMBEDDING_HF_MODEL_NAME:BAAI/bge-small-en-v1.5}
> > sagemaker: llm_endpoint_name: ${PGPT_SAGEMAKER_LLM_ENDPOINT_NAME:} embedding_endpoint_name: ${PGPT_SAGEMAKER_EMBEDDING_ENDPOINT_NAME:}
> > ui: enabled: true path: / `
> > After doing this all the container starts, but then I get this error message:
> > **PermissionError: [Errno 13] Permission denied: '/home/worker/app/models/cache'** **There was a problem when trying to write in your cache folder (/nonexistent/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.** **matplotlib - Matplotlib created a temporary cache directory at /tmp/matplotlib-ofvtqk2r because the default path (/nonexistent/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
> > 22:13:19.478 [INFO ] matplotlib.font_manager - generated new fontManager**
> > I am sorry that I am probably asking too much, I just want it to work
> 
> You need tto provide read and write permission to model/cache directory inside the container

How can i provide read and write permission to container that wont even start? Is not that i can go into the image and tweak some settings. The model /cache folder that suppose to be in my docker /private-gpt directory is empty. There is nothing there. It seems that is wasn't bind to the same folder on the image side.

**Comment by qdm12** [comment]
> How can i provide read and write permission to container that wont even start? Is not that i can go into the image and tweak some settings. The model /cache folder that suppose to be in my docker /private-gpt directory is empty.

You shouldn't get this error if you're using the image from my branch. It got solved by https://github.com/qdm12/private-gpt/pull/5/commits/3affdcedc9bc23a0efbdbb95e756c88ea777fb2d

**Comment by mrepetto-certx** [comment]
@qdm12 I'm still getting permission denied. I'm on Ubuntu 22.04.

**Comment by qdm12** [comment]
If you get permission denied, it's a configuration problem on your end about file ownership/permissions. If you cannot be bothered, just run the container as root with `--user=root` or `--user=0`.

**Comment by mrepetto-certx** [comment]
You are right. I think it is because I'm running it using Podman. I solved this by commenting `USER worker` in the `dockerfile.external`. But to be honest, I do not know if this is recommended as I'm not a cybersec specialist @qdm12, let me know your opinion.
