### ISSUE TITLE
[BUG] cannot import name 'BaseQueryEngine' from 'llama_index.core' 

### ISSUE THREAD

**Issue by zdavatz** [zylon-ai/private-gpt#2085]
### Pre-check

- [X] I have searched the existing issues and none cover this bug.

### Description

1. cd `/Users/zdavatz/Documents/software/privateGPT
2. I am doing `poetry run python3.11 -m private_gpt`
3. Then I get
```
18:07:28.480 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/zdavatz/Documents/software/privateGPT/private_gpt/__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "/Users/zdavatz/Documents/software/privateGPT/private_gpt/main.py", line 4, in <module>
    from private_gpt.launcher import create_app
  File "/Users/zdavatz/Documents/software/privateGPT/private_gpt/launcher.py", line 8, in <module>
    from llama_index.core.callbacks import CallbackManager
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/__init__.py", line 21, in <module>
    from llama_index.indices import (
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/indices/__init__.py", line 4, in <module>
    from llama_index.indices.composability.graph import ComposableGraph
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/indices/composability/__init__.py", line 4, in <module>
    from llama_index.indices.composability.graph import ComposableGraph
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/indices/composability/graph.py", line 5, in <module>
    from llama_index.core import BaseQueryEngine
ImportError: cannot import name 'BaseQueryEngine' from 'llama_index.core' (/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/core/__init__.py)
```

### Steps to Reproduce

see above.

### Expected Behavior

App should start

### Actual Behavior

Does not start

### Environment

macOS, m1

### Setup Checklist

- [X] Confirm that you have followed the installation instructions in the project’s documentation.
- [ ] Check that you are using the latest version of the project.
- [ ] Verify disk space availability for model storage and data processing.
- [ ] Ensure that you have the necessary permissions to run the project.

### NVIDIA GPU Setup Checklist

- [ ] Check that the all CUDA dependencies are installed and are compatible with your GPU (refer to [CUDA's documentation](https://docs.nvidia.com/deploy/cuda-compatibility/#frequently-asked-questions))
- [ ] Ensure an NVIDIA GPU is installed and recognized by the system (run `nvidia-smi` to verify).
- [ ] Ensure proper permissions are set for accessing GPU resources.
- [ ] Docker users - Verify that the NVIDIA Container Toolkit is configured correctly (e.g. run `sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi`)

**Comment by zdavatz** [comment]
1. same result when doing: `PGPT_PROFILES=ollama make run`
2. 
```
poetry run python -m private_gpt
18:13:39.716 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'ollama']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/zdavatz/Documents/software/privateGPT/private_gpt/__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "/Users/zdavatz/Documents/software/privateGPT/private_gpt/main.py", line 4, in <module>
    from private_gpt.launcher import create_app
  File "/Users/zdavatz/Documents/software/privateGPT/private_gpt/launcher.py", line 8, in <module>
    from llama_index.core.callbacks import CallbackManager
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/__init__.py", line 21, in <module>
    from llama_index.indices import (
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/indices/__init__.py", line 4, in <module>
    from llama_index.indices.composability.graph import ComposableGraph
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/indices/composability/__init__.py", line 4, in <module>
    from llama_index.indices.composability.graph import ComposableGraph
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/indices/composability/graph.py", line 5, in <module>
    from llama_index.core import BaseQueryEngine
ImportError: cannot import name 'BaseQueryEngine' from 'llama_index.core' (/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/core/__init__.py)
make: *** [run] Error 1
```

**Comment by vinodhanvino** [comment]
check the version of llama index and reinstall version = 0.11.10, else.
find this from llama_index.core import BaseQueryEngine replace with 
"from llama_index.core.base.base_query_engine import BaseQueryEngine"

**Comment by zdavatz** [comment]
Thank you. I done `pip3.11 install llama-index==0.11.10` but I am still getting the same result.

**Comment by zdavatz** [comment]
> from llama_index.core.base.base_query_engine import BaseQueryEngine

I have to changes this in all of these files:
```
➜  privateGPT git:(main) grep -ri "from llama_index.core import BaseQueryEngine" .
./.venv/lib/python3.11/site-packages/llama_index/retrievers/recursive_retriever.py:from llama_index.core import BaseQueryEngine, BaseRetriever
./.venv/lib/python3.11/site-packages/llama_index/indices/struct_store/pandas.py:from llama_index.core import BaseQueryEngine, BaseRetriever
./.venv/lib/python3.11/site-packages/llama_index/indices/struct_store/sql_query.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/indices/struct_store/json_query.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/indices/struct_store/sql.py:from llama_index.core import BaseQueryEngine, BaseRetriever
./.venv/lib/python3.11/site-packages/llama_index/indices/empty/base.py:from llama_index.core import BaseQueryEngine, BaseRetriever
./.venv/lib/python3.11/site-packages/llama_index/indices/composability/graph.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/indices/multi_modal/base.py:from llama_index.core import BaseQueryEngine, BaseRetriever
./.venv/lib/python3.11/site-packages/llama_index/indices/query/base.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/indices/base.py:from llama_index.core import BaseQueryEngine, BaseRetriever
./.venv/lib/python3.11/site-packages/llama_index/tools/query_engine.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/agent/types.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/langchain_helpers/agents/tools.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/evaluation/batch_runner.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/evaluation/benchmarks/hotpotqa.py:from llama_index.core import BaseQueryEngine, BaseRetriever
./.venv/lib/python3.11/site-packages/llama_index/evaluation/eval_utils.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/chat_engine/condense_question.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/query_engine/custom.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/query_engine/knowledge_graph_query_engine.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/query_engine/citation_query_engine.py:from llama_index.core import BaseQueryEngine, BaseRetriever
./.venv/lib/python3.11/site-packages/llama_index/query_engine/sql_join_query_engine.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/query_engine/retriever_query_engine.py:from llama_index.core import BaseQueryEngine, BaseRetriever
./.venv/lib/python3.11/site-packages/llama_index/query_engine/retry_query_engine.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/query_engine/router_query_engine.py:from llama_index.core import BaseQueryEngine, BaseRetriever
./.venv/lib/python3.11/site-packages/llama_index/query_engine/cogniswitch_query_engine.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/query_engine/multistep_query_engine.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/query_engine/__init__.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/query_engine/pandas_query_engine.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/query_engine/graph_query_engine.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/query_engine/sub_question_query_engine.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/query_engine/flare/base.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/query_engine/transform_query_engine.py:from llama_index.core import BaseQueryEngine
./.venv/lib/python3.11/site-packages/llama_index/query_engine/retry_source_query_engine.py:from llama_index.core import BaseQueryEngine
```

**Comment by zdavatz** [comment]
1. Ok, I done: `grep -ilr 'from llama_index.core import BaseQueryEngine' * | xargs -I@ sed -i '' 's/from llama_index.core import BaseQueryEngine/from llama_index.core.base.base_query_engine import BaseQueryEngine/g' @`
2. I am still getting:
```
➜  privateGPT git:(main) PGPT_PROFILES=ollama make run                                                                                                         
poetry run python -m private_gpt
09:09:34.828 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'ollama']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/zdavatz/Documents/software/privateGPT/private_gpt/__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "/Users/zdavatz/Documents/software/privateGPT/private_gpt/main.py", line 4, in <module>
    from private_gpt.launcher import create_app
  File "/Users/zdavatz/Documents/software/privateGPT/private_gpt/launcher.py", line 8, in <module>
    from llama_index.core.callbacks import CallbackManager
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/__init__.py", line 21, in <module>
    from llama_index.indices import (
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/indices/__init__.py", line 4, in <module>
    from llama_index.indices.composability.graph import ComposableGraph
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/indices/composability/__init__.py", line 4, in <module>
    from llama_index.indices.composability.graph import ComposableGraph
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/indices/composability/graph.py", line 7, in <module>
    from llama_index.indices.base import BaseIndex
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/indices/base.py", line 6, in <module>
    from llama_index.chat_engine.types import BaseChatEngine, ChatMode
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/chat_engine/__init__.py", line 1, in <module>
    from llama_index.chat_engine.condense_question import CondenseQuestionChatEngine
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/chat_engine/condense_question.py", line 6, in <module>
    from llama_index.chat_engine.types import (
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/chat_engine/types.py", line 14, in <module>
    from llama_index.tools import ToolOutput
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/tools/__init__.py", line 5, in <module>
    from llama_index.tools.query_engine import QueryEngineTool
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/tools/query_engine.py", line 3, in <module>
    from llama_index.core import BaseQueryEngine
ImportError: cannot import name 'BaseQueryEngine' from 'llama_index.core' (/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/llama_index/core/__init__.py)
make: *** [run] Error 1
```

**Comment by zdavatz** [comment]
1. Replacement worked with this command on Mac: `grep -rli "from llama_index.core import BaseQueryEngine" . | xargs sed -i 's/from llama_index.core import BaseQueryEngine/from llama_index.core.base.base_query_engine import BaseQueryEngine/g'`
2. But still same error.

**Comment by jaluma** [comment]
How do you install dependencies? Currently, we are using `llama-index-core==0.10.58`.
Can you try removing .venv and installing using:
`poetry install --all-extras --no-cache`

**Comment by zdavatz** [comment]
This seems to help. Now I am getting:
```
Using python3.11 (3.11.4)
12:28:51.110 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'ollama']
12:28:53.840 [INFO    ] private_gpt.components.llm.llm_component - Initializing the LLM in mode=ollama
12:28:53.856 [WARNING ]  private_gpt.utils.ollama - [Errno 61] Connection refused, retrying in 0 seconds...
12:28:53.856 [WARNING ]  private_gpt.utils.ollama - [Errno 61] Connection refused, retrying in 7.189137648894498 seconds...
12:29:01.053 [WARNING ]  private_gpt.utils.ollama - [Errno 61] Connection refused, retrying in 13.564974849898535 seconds...
12:29:14.626 [WARNING ]  private_gpt.utils.ollama - [Errno 61] Connection refused, retrying in 20.340348493896336 seconds...
Traceback (most recent call last):
  File "/Users/zdavatz/Library/Caches/pypoetry/virtualenvs/private-gpt-R_OQ3zM3-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/Users/zdavatz/Library/Caches/pypoetry/virtualenvs/private-gpt-R_OQ3zM3-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/Library/Caches/pypoetry/virtualenvs/private-gpt-R_OQ3zM3-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/Users/zdavatz/Library/Caches/pypoetry/virtualenvs/private-gpt-R_OQ3zM3-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/Library/Caches/pypoetry/virtualenvs/private-gpt-R_OQ3zM3-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/Users/zdavatz/Library/Caches/pypoetry/virtualenvs/private-gpt-R_OQ3zM3-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/Library/Caches/pypoetry/virtualenvs/private-gpt-R_OQ3zM3-py3.11/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/Library/Caches/pypoetry/virtualenvs/private-gpt-R_OQ3zM3-py3.11/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/zdavatz/Library/Caches/pypoetry/virtualenvs/private-gpt-R_OQ3zM3-py3.11/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:
```

**Comment by zdavatz** [comment]
Thank you, I did not have https://github.com/ollama/ollama?tab=readme-ov-file installed.
