### ISSUE TITLE
[BUG]  Docker Desktop throwing me a bunch of errors before crashing

### ISSUE THREAD

**Issue by paulsybrandy** [zylon-ai/private-gpt#2106]
### Pre-check

- [X] I have searched the existing issues and none cover this bug.

### Description

Honestly, I don't even have a clue what is happening with this but I will post the output so someone might make sense of it. A permissions error I believe... lots of them actually! I start the process with docker compose up -d and it pulls what it needs to. The process completes entirely from what I can see. It is when it runs after the install where the issue starts.

### Steps to Reproduce

1. Open command prompt and clone git repo
2. Go into directory
3. Run `docker compose up -d`
4.  It downloads, pulls and installs (takes about 3-4 minutes)
5. Then I try to go to 127.0.0.1:8001 which was not successful
6. I open Docker Desktop and go to the container for private GPT and saw the vast amount of errors that have populated

### Expected Behavior

After the successful pull of the files and the install (which did seem to be successful), it should have been running and going to the localhost port should have displayed the start up screen which it did not.

### Actual Behavior

As mentioned in the Steps to Reproduce

### Environment

Windows 11 build 22635.4000, AMD Ryzen 7 5800H with Radeon Graphics, 32GB RAM, 

### Additional Information

Down below it goes through a Setup Checklist to which I am not sure what I need to do to achieve this. This may be part if not most of the issue. 

### Version

0.6.2

### Setup Checklist

- [X] Confirm that you have followed the installation instructions in the project’s documentation.
- [X] Check that you are using the latest version of the project.
- [X] Verify disk space availability for model storage and data processing.
- [ ] Ensure that you have the necessary permissions to run the project.

### NVIDIA GPU Setup Checklist

- [ ] Check that the all CUDA dependencies are installed and are compatible with your GPU (refer to [CUDA's documentation](https://docs.nvidia.com/deploy/cuda-compatibility/#frequently-asked-questions))
- [ ] Ensure an NVIDIA GPU is installed and recognized by the system (run `nvidia-smi` to verify).
- [ ] Ensure proper permissions are set for accessing GPU resources.
- [ ] Docker users - Verify that the NVIDIA Container Toolkit is configured correctly (e.g. run `sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi`)

**Comment by jaluma** [comment]
Can you share your docker logs?

**Comment by paulsybrandy** [comment]
2024-10-18 08:39:47 ollama-1  | 2024/10/18 12:39:47 routes.go:1158: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/root/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"
2024-10-18 08:39:47 ollama-1  | time=2024-10-18T12:39:47.141Z level=INFO source=images.go:754 msg="total blobs: 0"
2024-10-18 08:39:47 ollama-1  | time=2024-10-18T12:39:47.145Z level=INFO source=images.go:761 msg="total unused blobs removed: 0"
2024-10-18 08:39:47 ollama-1  | time=2024-10-18T12:39:47.150Z level=INFO source=routes.go:1205 msg="Listening on [::]:11434 (version 0.3.13)"
2024-10-18 08:39:47 ollama-1  | time=2024-10-18T12:39:47.154Z level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu cpu_avx cpu_avx2 cuda_v11 cuda_v12]"
2024-10-18 08:39:47 ollama-1  | time=2024-10-18T12:39:47.154Z level=INFO source=gpu.go:199 msg="looking for compatible GPUs"
2024-10-18 08:39:47 ollama-1  | time=2024-10-18T12:39:47.171Z level=INFO source=gpu.go:347 msg="no compatible GPUs were discovered"
2024-10-18 08:39:47 ollama-1  | time=2024-10-18T12:39:47.171Z level=INFO source=types.go:107 msg="inference compute" id=0 library=cpu variant=avx2 compute="" driver=0.0 name="" total="14.1 GiB" available="9.0 GiB"
2024-10-18 08:39:48 private-gpt-1  | 12:39:48.120 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'docker']
2024-10-18 08:39:54 private-gpt-1  | There was a problem when trying to write in your cache folder (/nonexistent/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
2024-10-18 08:39:54 private-gpt-1  | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
2024-10-18 08:39:57 private-gpt-1  | 12:39:57.227 [WARNING ]                matplotlib - Matplotlib created a temporary cache directory at /tmp/matplotlib-g5jyb9q0 because the default path (/nonexistent/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
2024-10-18 08:39:57 private-gpt-1  | 12:39:57.624 [INFO    ]   matplotlib.font_manager - generated new fontManager
2024-10-18 08:39:59 private-gpt-1  | Traceback (most recent call last):
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
2024-10-18 08:39:59 private-gpt-1  |     return self._context[key]
2024-10-18 08:39:59 private-gpt-1  |            ~~~~~~~~~~~~~^^^^^
2024-10-18 08:39:59 private-gpt-1  | KeyError: <class 'private_gpt.ui.ui.PrivateGptUi'>
2024-10-18 08:39:59 private-gpt-1  | 
2024-10-18 08:39:59 private-gpt-1  | During handling of the above exception, another exception occurred:
2024-10-18 08:39:59 private-gpt-1  | 
2024-10-18 08:39:59 private-gpt-1  | Traceback (most recent call last):
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
2024-10-18 08:39:59 private-gpt-1  |     return self._context[key]
2024-10-18 08:39:59 private-gpt-1  |            ~~~~~~~~~~~~~^^^^^
2024-10-18 08:39:59 private-gpt-1  | KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>
2024-10-18 08:39:59 private-gpt-1  | 
2024-10-18 08:39:59 private-gpt-1  | During handling of the above exception, another exception occurred:
2024-10-18 08:39:59 private-gpt-1  | 
2024-10-18 08:39:59 private-gpt-1  | Traceback (most recent call last):
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
2024-10-18 08:39:59 private-gpt-1  |     return self._context[key]
2024-10-18 08:39:59 private-gpt-1  |            ~~~~~~~~~~~~~^^^^^
2024-10-18 08:39:59 private-gpt-1  | KeyError: <class 'private_gpt.components.llm.llm_component.LLMComponent'>
2024-10-18 08:39:59 private-gpt-1  | 
2024-10-18 08:39:59 private-gpt-1  | During handling of the above exception, another exception occurred:
2024-10-18 08:39:59 private-gpt-1  | 
2024-10-18 08:39:59 private-gpt-1  | Traceback (most recent call last):
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 270, in hf_raise_for_status
2024-10-18 08:39:59 private-gpt-1  |     response.raise_for_status()
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
2024-10-18 08:39:59 private-gpt-1  |     raise HTTPError(http_error_msg, response=self)
2024-10-18 08:39:59 private-gpt-1  | requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json
2024-10-18 08:39:59 private-gpt-1  | 
2024-10-18 08:39:59 private-gpt-1  | The above exception was the direct cause of the following exception:
2024-10-18 08:39:59 private-gpt-1  | 
2024-10-18 08:39:59 private-gpt-1  | Traceback (most recent call last):
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/transformers/utils/hub.py", line 398, in cached_file
2024-10-18 08:39:59 private-gpt-1  |     resolved_file = hf_hub_download(
2024-10-18 08:39:59 private-gpt-1  |                     ^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
2024-10-18 08:39:59 private-gpt-1  |     return fn(*args, **kwargs)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1374, in hf_hub_download
2024-10-18 08:39:59 private-gpt-1  |     raise head_call_error
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1247, in hf_hub_download
2024-10-18 08:39:59 private-gpt-1  |     metadata = get_hf_file_metadata(
2024-10-18 08:39:59 private-gpt-1  |                ^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
2024-10-18 08:39:59 private-gpt-1  |     return fn(*args, **kwargs)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1624, in get_hf_file_metadata
2024-10-18 08:39:59 private-gpt-1  |     r = _request_wrapper(
2024-10-18 08:39:59 private-gpt-1  |         ^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 402, in _request_wrapper
2024-10-18 08:39:59 private-gpt-1  |     response = _request_wrapper(
2024-10-18 08:39:59 private-gpt-1  |                ^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 426, in _request_wrapper
2024-10-18 08:39:59 private-gpt-1  |     hf_raise_for_status(response)
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 286, in hf_raise_for_status
2024-10-18 08:39:59 private-gpt-1  |     raise GatedRepoError(message, response) from e
2024-10-18 08:39:59 private-gpt-1  | huggingface_hub.utils._errors.GatedRepoError: 401 Client Error. (Request ID: Root=1-67125723-2ef98e760e870caf653ff648;0db3f70e-bab8-4974-bfcd-7eacc5d45f8d)
2024-10-18 08:39:59 private-gpt-1  | 
2024-10-18 08:39:59 private-gpt-1  | Cannot access gated repo for url https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json.
2024-10-18 08:39:59 private-gpt-1  | Access to model mistralai/Mistral-7B-Instruct-v0.2 is restricted. You must have access to it and be authenticated to access it. Please log in.
2024-10-18 08:39:59 private-gpt-1  | 
2024-10-18 08:39:59 private-gpt-1  | The above exception was the direct cause of the following exception:
2024-10-18 08:39:59 private-gpt-1  | 
2024-10-18 08:39:59 private-gpt-1  | Traceback (most recent call last):
2024-10-18 08:39:59 private-gpt-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-10-18 08:39:59 private-gpt-1  |   File "<frozen runpy>", line 88, in _run_code
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/private_gpt/__main__.py", line 5, in <module>
2024-10-18 08:39:59 private-gpt-1  |     from private_gpt.main import app
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/private_gpt/main.py", line 6, in <module>
2024-10-18 08:39:59 private-gpt-1  |     app = create_app(global_injector)
2024-10-18 08:39:59 private-gpt-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/private_gpt/launcher.py", line 63, in create_app
2024-10-18 08:39:59 private-gpt-1  |     ui = root_injector.get(PrivateGptUi)
2024-10-18 08:39:59 private-gpt-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
2024-10-18 08:39:59 private-gpt-1  |     return function(*args, **kwargs)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
2024-10-18 08:39:59 private-gpt-1  |     provider_instance = scope_instance.get(interface, binding.provider)
2024-10-18 08:39:59 private-gpt-1  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
2024-10-18 08:39:59 private-gpt-1  |     return function(*args, **kwargs)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
2024-10-18 08:39:59 private-gpt-1  |     instance = self._get_instance(key, provider, self.injector)
2024-10-18 08:39:59 private-gpt-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
2024-10-18 08:39:59 private-gpt-1  |     return provider.get(injector)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
2024-10-18 08:39:59 private-gpt-1  |     return injector.create_object(self._cls)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
2024-10-18 08:39:59 private-gpt-1  |     self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 1031, in call_with_injection
2024-10-18 08:39:59 private-gpt-1  |     dependencies = self.args_to_inject(
2024-10-18 08:39:59 private-gpt-1  |                    ^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
2024-10-18 08:39:59 private-gpt-1  |     return function(*args, **kwargs)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 1079, in args_to_inject
2024-10-18 08:39:59 private-gpt-1  |     instance: Any = self.get(interface)
2024-10-18 08:39:59 private-gpt-1  |                     ^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
2024-10-18 08:39:59 private-gpt-1  |     return function(*args, **kwargs)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
2024-10-18 08:39:59 private-gpt-1  |     provider_instance = scope_instance.get(interface, binding.provider)
2024-10-18 08:39:59 private-gpt-1  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
2024-10-18 08:39:59 private-gpt-1  |     return function(*args, **kwargs)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
2024-10-18 08:39:59 private-gpt-1  |     instance = self._get_instance(key, provider, self.injector)
2024-10-18 08:39:59 private-gpt-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
2024-10-18 08:39:59 private-gpt-1  |     return provider.get(injector)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
2024-10-18 08:39:59 private-gpt-1  |     return injector.create_object(self._cls)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
2024-10-18 08:39:59 private-gpt-1  |     self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 1031, in call_with_injection
2024-10-18 08:39:59 private-gpt-1  |     dependencies = self.args_to_inject(
2024-10-18 08:39:59 private-gpt-1  |                    ^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
2024-10-18 08:39:59 private-gpt-1  |     return function(*args, **kwargs)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 1079, in args_to_inject
2024-10-18 08:39:59 private-gpt-1  |     instance: Any = self.get(interface)
2024-10-18 08:39:59 private-gpt-1  |                     ^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
2024-10-18 08:39:59 private-gpt-1  |     return function(*args, **kwargs)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
2024-10-18 08:39:59 private-gpt-1  |     provider_instance = scope_instance.get(interface, binding.provider)
2024-10-18 08:39:59 private-gpt-1  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
2024-10-18 08:39:59 private-gpt-1  |     return function(*args, **kwargs)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
2024-10-18 08:39:59 private-gpt-1  |     instance = self._get_instance(key, provider, self.injector)
2024-10-18 08:39:59 private-gpt-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
2024-10-18 08:39:59 private-gpt-1  |     return provider.get(injector)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
2024-10-18 08:39:59 private-gpt-1  |     return injector.create_object(self._cls)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
2024-10-18 08:39:59 private-gpt-1  |     self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 1040, in call_with_injection
2024-10-18 08:39:59 private-gpt-1  |     return callable(*full_args, **dependencies)
2024-10-18 08:39:59 private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/private_gpt/components/llm/llm_component.py", line 27, in __init__
2024-10-18 08:39:59 private-gpt-1  |     AutoTokenizer.from_pretrained(
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 782, in from_pretrained
2024-10-18 08:39:59 private-gpt-1  |     config = AutoConfig.from_pretrained(
2024-10-18 08:39:59 private-gpt-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1111, in from_pretrained
2024-10-18 08:39:59 private-gpt-1  |     config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
2024-10-18 08:39:59 private-gpt-1  |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/transformers/configuration_utils.py", line 633, in get_config_dict
2024-10-18 08:39:59 private-gpt-1  |     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
2024-10-18 08:39:59 private-gpt-1  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/transformers/configuration_utils.py", line 688, in _get_config_dict
2024-10-18 08:39:59 private-gpt-1  |     resolved_config_file = cached_file(
2024-10-18 08:39:59 private-gpt-1  |                            ^^^^^^^^^^^^
2024-10-18 08:39:59 private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/transformers/utils/hub.py", line 416, in cached_file
2024-10-18 08:39:59 private-gpt-1  |     raise EnvironmentError(
2024-10-18 08:39:59 private-gpt-1  | OSError: You are trying to access a gated repo.
2024-10-18 08:39:59 private-gpt-1  | Make sure to have access to it at https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2.
2024-10-18 08:39:59 private-gpt-1  | 401 Client Error. (Request ID: Root=1-67125723-2ef98e760e870caf653ff648;0db3f70e-bab8-4974-bfcd-7eacc5d45f8d)
2024-10-18 08:39:59 private-gpt-1  | 
2024-10-18 08:39:59 private-gpt-1  | Cannot access gated repo for url https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json.
2024-10-18 08:39:59 private-gpt-1  | Access to model mistralai/Mistral-7B-Instruct-v0.2 is restricted. You must have access to it and be authenticated to access it. Please log in.

**Comment by jaluma** [comment]
> Cannot access gated repo for url https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json.
> | Access to model mistralai/Mistral-7B-Instruct-v0.2 is restricted. You must have access to it and be authenticated to access it. Please log in.

Please, review the official doc to create a HF token: https://docs.privategpt.dev/installation/getting-started/troubleshooting#downloading-gated-and-private-models
