### ISSUE TITLE
[BUG] LLAMA-CPP-Python issue

### ISSUE THREAD

**Issue by ashunaveed** [zylon-ai/private-gpt#2109]
### Pre-check

- [X] I have searched the existing issues and none cover this bug.

### Description

(gpt1) ashu@MSI:/mnt/c/Users/genco/Documents/gpt$ pyenv install 3.11
pyenv: /home/ashu/.pyenv/versions/3.11.10 already exists
continue with installation? (y/N)
(gpt1) ashu@MSI:/mnt/c/Users/genco/Documents/gpt$ pyenv local 3.11
(gpt1) ashu@MSI:/mnt/c/Users/genco/Documents/gpt$ curl -sSL https://install.python-poetry.org | python3 -
Retrieving Poetry metadata

The latest version (1.8.4) is already installed.
(gpt1) ashu@MSI:/mnt/c/Users/genco/Documents/gpt$ brew install make
Warning: make 4.4.1 is already installed and up-to-date.
To reinstall 4.4.1, run:
  brew reinstall make
(gpt1) ashu@MSI:/mnt/c/Users/genco/Documents/gpt$ poetry install --extras "ui llms-llama-cpp embeddings-huggingface vector-stores-qdrant"
Installing dependencies from lock file

Package operations: 1 install, 40 updates, 0 removals

  - Downgrading charset-normalizer (3.4.0 -> 3.3.2)
  - Downgrading frozenlist (1.5.0 -> 1.4.1)
  - Downgrading aiohappyeyeballs (2.4.3 -> 2.4.0)
  - Downgrading anyio (4.6.2.post1 -> 4.6.0)
  - Downgrading fsspec (2024.10.0 -> 2024.9.0)
  - Downgrading grpcio (1.67.0 -> 1.66.1)
  - Downgrading httpcore (1.0.6 -> 1.0.5)
  - Downgrading marshmallow (3.23.0 -> 3.22.0)
  - Downgrading nvidia-nvjitlink-cu12 (12.6.77 -> 12.6.68)
  - Downgrading pyparsing (3.2.0 -> 3.1.4)
  - Downgrading setuptools (75.2.0 -> 75.1.0)
  - Downgrading yarl (1.16.0 -> 1.12.1)
  - Downgrading aiohttp (3.10.10 -> 3.10.6)
  - Downgrading huggingface-hub (0.26.1 -> 0.25.1)
  - Downgrading networkx (3.4.2 -> 3.3)
  - Downgrading sqlalchemy (2.0.36 -> 2.0.35)
  - Downgrading tiktoken (0.8.0 -> 0.7.0)
  - Downgrading httptools (0.6.4 -> 0.6.1)
  - Downgrading llama-index-core (0.11.19 -> 0.11.13.post1)
  - Downgrading rich (13.9.3 -> 13.8.1)
  - Downgrading starlette (0.41.0 -> 0.38.6)
  - Downgrading tokenizers (0.20.1 -> 0.20.0)
  - Downgrading uvloop (0.21.0 -> 0.20.0)
  - Downgrading distlib (0.3.9 -> 0.3.8)
  - Downgrading dnspython (2.7.0 -> 2.6.1)
  - Downgrading fastapi (0.115.3 -> 0.115.0)
  - Downgrading orjson (3.10.10 -> 3.10.7)
  - Downgrading transformers (4.46.0 -> 4.45.0)
  - Downgrading uvicorn (0.32.0 -> 0.30.6)
  - Downgrading coverage (7.6.4 -> 7.6.1)
  - Downgrading llama-cpp-python (0.3.1 -> 0.2.90)
  - Downgrading pydantic-settings (2.6.0 -> 2.5.2)
  - Downgrading qdrant-client (1.12.0 -> 1.11.3)
  - Downgrading ruff (0.7.1 -> 0.6.7)
  - Downgrading sentence-transformers (3.2.1 -> 3.1.1)
  - Downgrading virtualenv (20.27.0 -> 20.26.5)
  - Downgrading black (24.10.0 -> 24.8.0)
  - Downgrading gradio (4.44.1 -> 4.44.0)
  - Installing llama-index-llms-llama-cpp (0.2.2)
  - Downgrading llama-index-vector-stores-qdrant (0.3.2 -> 0.3.0)
  - Downgrading mypy (1.13.0 -> 1.11.2)

Installing the current project: private-gpt (0.6.2)
(gpt1) ashu@MSI:/mnt/c/Users/genco/Documents/gpt$ poetry run python scripts/setup
10:24:39.633 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
Downloading embedding dunzhang/stella_en_1.5B_v5
Fetching 41 files: 100%|███████████████████████████████████████████████████████████████| 41/41 [00:00<00:00, 347.58it/s]
Embedding model downloaded!
Downloading LLM Meta-Llama-3.1-8B-Instruct-Q8_0.gguf
10:24:41.323 [WARNING ]               py.warnings - /home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

LLM model downloaded!
Downloading tokenizer meta-llama/Meta-Llama-3.1-8B-Instruct
Tokenizer downloaded!
Setup done
(gpt1) ashu@MSI:/mnt/c/Users/genco/Documents/gpt$ export PGPT_PROFILES=local
(gpt1) ashu@MSI:/mnt/c/Users/genco/Documents/gpt$ make run
poetry run python -m private_gpt
10:25:01.791 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'local']
10:25:07.465 [INFO    ] private_gpt.components.llm.llm_component - Initializing the LLM in mode=llamacpp
10:25:07.529 [WARNING ]               py.warnings - /home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:132: UserWarning: Field "model_url" in LlamaCPP has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(

10:25:07.529 [WARNING ]               py.warnings - /home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:132: UserWarning: Field "model_path" in LlamaCPP has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(

10:25:07.529 [WARNING ]               py.warnings - /home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:132: UserWarning: Field "model_kwargs" in LlamaCPP has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(

Traceback (most recent call last):
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.ui.ui.PrivateGptUi'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.components.llm.llm_component.LLMComponent'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/c/Users/genco/Documents/gpt/private_gpt/__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "/mnt/c/Users/genco/Documents/gpt/private_gpt/main.py", line 6, in <module>
    app = create_app(global_injector)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/genco/Documents/gpt/private_gpt/launcher.py", line 66, in create_app
    ui = root_injector.get(PrivateGptUi)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 976, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 802, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 813, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1000, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1041, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1089, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 976, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 802, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 813, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1000, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1041, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1089, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 976, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 802, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 813, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1000, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1050, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/genco/Documents/gpt/private_gpt/components/llm/llm_component.py", line 63, in __init__
    self.llm = LlamaCPP(
               ^^^^^^^^^
  File "/home/ashu/.cache/pypoetry/virtualenvs/private-gpt-I_MJhhDm-py3.11/lib/python3.11/site-packages/llama_index/llms/llama_cpp/base.py", line 157, in __init__
    raise ValueError(
ValueError: Provided model path does not exist. Please check the path or provide a model_url to download.
make: *** [Makefile:36: run] Error 1

### Steps to Reproduce

1. run everything as shown.
2. run into error.

### Expected Behavior

complete installation

### Actual Behavior

failed installation.

### Environment

WSL ubuntu nvidia rtx4060.

### Additional Information

_No response_

### Version

_No response_

### Setup Checklist

- [X] Confirm that you have followed the installation instructions in the project’s documentation.
- [X] Check that you are using the latest version of the project.
- [X] Verify disk space availability for model storage and data processing.
- [X] Ensure that you have the necessary permissions to run the project.

### NVIDIA GPU Setup Checklist

- [X] Check that the all CUDA dependencies are installed and are compatible with your GPU (refer to [CUDA's documentation](https://docs.nvidia.com/deploy/cuda-compatibility/#frequently-asked-questions))
- [X] Ensure an NVIDIA GPU is installed and recognized by the system (run `nvidia-smi` to verify).
- [X] Ensure proper permissions are set for accessing GPU resources.
- [ ] Docker users - Verify that the NVIDIA Container Toolkit is configured correctly (e.g. run `sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi`)

**Comment by jaluma** [comment]
Are there any more logs or can you explain us what happen when you try to open http://0.0.0.0:8001/?
