### ISSUE TITLE
[BUG] TypeError: llama_index.core.ingestion.pipeline.run_transformations() got multiple values for keyword argument 'show_progress'

### ISSUE THREAD

**Issue by yaziciali** [zylon-ai/private-gpt#2133]
### Pre-check

- [X] I have searched the existing issues and none cover this bug.

### Description

Hi,
I get this error, and couldn't resolve it,
Can you help me?

file_name: image__vector_store.json, extension: .json, reader_cls: <class 'llama_index.core.readers.json.JSONReader'>
Traceback (most recent call last):
  File "/Users/user/AI/private-gpt/scripts/ingest_folder.py", line 122, in <module>
    worker.ingest_folder(root_path, args.ignored)
  File "/Users/user/AI/private-gpt/scripts/ingest_folder.py", line 58, in ingest_folder
    self._ingest_all(self._files_under_root_folder)
  File "/Users/user/AI/private-gpt/scripts/ingest_folder.py", line 62, in _ingest_all
    self.ingest_service.bulk_ingest([(str(p.name), p) for p in files_to_ingest])
  File "/Users/user/AI/private-gpt/private_gpt/server/ingest/ingest_service.py", line 87, in bulk_ingest
    documents = self.ingest_component.bulk_ingest(files)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/AI/private-gpt/private_gpt/components/ingest/ingest_component.py", line 135, in bulk_ingest
    saved_documents.extend(self._save_docs(documents))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/AI/private-gpt/private_gpt/components/ingest/ingest_component.py", line 143, in _save_docs
    self._index.insert(document, show_progress=True)
  File "/Users/user/AI/private-gpt/.venv/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 209, in insert
    nodes = run_transformations(
            ^^^^^^^^^^^^^^^^^^^^
TypeError: llama_index.core.ingestion.pipeline.run_transformations() got multiple values for keyword argument 'show_progress'
make: *** [ingest] Error 1

### Steps to Reproduce

PGPT_PROFILES=ollama make ingest ../ING -- --watch --log-file ../LOGS/privategpt_ingest.log

Ctrl+c after a while
Then try again

### Expected Behavior

ingest documents

### Actual Behavior

error

### Environment

Mac ARM cpu and gpu with python 3.11

### Setup Checklist

- [X] Confirm that you have followed the installation instructions in the project’s documentation.
- [X] Check that you are using the latest version of the project.
- [X] Verify disk space availability for model storage and data processing.
- [X] Ensure that you have the necessary permissions to run the project.

### NVIDIA GPU Setup Checklist

- [ ] Check that the all CUDA dependencies are installed and are compatible with your GPU (refer to [CUDA's documentation](https://docs.nvidia.com/deploy/cuda-compatibility/#frequently-asked-questions))
- [ ] Ensure an NVIDIA GPU is installed and recognized by the system (run `nvidia-smi` to verify).
- [X] Ensure proper permissions are set for accessing GPU resources.
- [ ] Docker users - Verify that the NVIDIA Container Toolkit is configured correctly (e.g. run `sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi`)

**Comment by jaluma** [comment]
Llama index has been bumped... I will update Llama Index to fix all dependencies issues.

**Comment by Abdur-Rahman29** [comment]
same error here. Please fix

**Comment by vedantt** [comment]
same error here. Please fix

**Comment by atharvadeopujari** [comment]
I am getting the same error

**Comment by BramMeerten** [comment]
I got the same error, I used the following workaround to get it working.
Edit the `ingest_component.py` file, in your case: `/Users/user/AI/private-gpt/private_gpt/components/ingest/ingest_component.py`:

```py
# Change following line:
self._index.insert(document, show_progress=True)

# to:
self._index.insert(document)
```
